window.alert("" + 1 + 0); // Displays "10"
window.alert("" - 1 + 0); // Displays "-1"
window.alert(true + false); // Displays "1"
window.alert(6 / "3"); // Displays "2"
window.alert("2" * "3"); // Displays "6"
window.alert(4 + 5 + "px"); // Displays "9px"
window.alert("$" + 4 + 5); // Displays "$45"
window.alert("4" - 2); // Displays "2"
window.alert("4px" - 2); // Displays "NaN"
window.alert("  -9  " + 5); // Displays "-9 5"
window.alert("  -9  " - 5); // Displays "-14"
window.alert(null + 1); // Displays "1"
window.alert(undefined + 1); // Displays "NaN"
window.alert(" \t \n" - 2); //Displays -2
