alert("" + 1 + 0); // Displays "10"
alert("" - 1 + 0); // Displays "-1"
alert(true + false); // Displays "1"
alert(6 / "3"); // Displays "2"
alert("2" * "3"); // Displays "6"
alert(4 + 5 + "px"); // Displays "9px"
alert("$" + 4 + 5); // Displays "$45"
alert("4" - 2); // Displays "2"
alert("4px" - 2); // Displays "NaN"
alert("  -9  " + 5); // Displays "-9 5"
alert("  -9  " - 5); // Displays "-14"
alert(null + 1); // Displays "1"
alert(undefined + 1); // Displays "NaN"
alert(" \t \n" - 2); //Displays -2
